server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: servicio-platos
          uri: lb://servicio-platos
          predicates:
            - Path=/platos/**
        - id: servicio-restaurantes
          uri: lb://servicio-restaurantes
          predicates:
            - Path=/restaurantes/**
        - id: servicio-clientes
          uri: lb://servicio-clientes
          predicates:
            - Path=/clientes/**
        - id: servicio-compras
          uri: lb://servicio-compras
          predicates:
            - Path=/compras/**
        - id: servicio-roles
          uri: lb://servicio-roles
          predicates:
            - Path=/roles/**
          
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"